#version 460

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout (binding = 0, rgba8) uniform writeonly image2D outImage;

layout(binding = 1) uniform UBO {
	vec2 cursorPos;
} u_ubo;

layout(binding = 2) uniform BrushProperties {
	vec4 color;
	float width;
	int circle;
} u_props;

void main()
{
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	
	ivec2 size = imageSize(outImage);
	if (pixel.x >= size.x || pixel.y >= size.y)
		return;

	vec4 color = vec4(0,0,0,1);
	if (u_ubo.cursorPos.x != -1.0)
	{
		vec2 pixelPos = vec2(pixel);
		if (u_props.circle != 0)
		{
			if (length(abs(pixelPos-u_ubo.cursorPos)) <= u_props.width)
				color = u_props.color;
			else
				return;
		}
		else
		{
			if (abs(u_ubo.cursorPos.x-pixelPos.x)<=u_props.width && abs(u_ubo.cursorPos.y-pixelPos.y)<=u_props.width)
				color = u_props.color;
			else
				return;
		}

		imageStore(outImage, pixel, color);
	}
}